export const commits = [
  {
    date: "2023.03",
    title: "feat: 가천대학교 소프트웨어전공 입학",
    description: "2025-2학기 기준 휴학생",
    branches: ["main"],
    color: "blue",
    position: 0,
  },
  {
    date: "2024.09",
    title: "feat: KKSC 1기 Frontend - Flutter 참여",
    description: "가천대학교 IT 동아리 KKSC 활동 (2024.09~2025.02)",
    branches: ["feature/club"],
    color: "purple",
    position: 1,
    isBranch: true,
  },
  {
    date: "2025.03",
    title: "feat: 자료구조 및 실습 과목 TA",
    description: "가천대학교 TA 활동 (2025.03~2025.08)",
    branches: ["main", "origin/main"],
    color: "blue",
    position: 0,
  },
  {
    date: "2025.03",
    title: "feat: UMC 8기 Node.js 챌린저 수료",
    description: "가천대학교 University Makeus Challenge 8기 (2025.03~2025.08)",
    branches: ["feature/club"],
    color: "purple",
    position: 2,
    isBranch: true,
  },
  {
    date: "2025.07",
    title: "feat: 멋쟁이 사자처럼 클라우드 엔지니어링 4기 수강",
    description: "Cloud Engineering Infra 과정 (2025.07~2026.01)",
    branches: ["feature/infra", "origin/feature/infra"],
    color: "yellow",
    position: 3,
    isBranch: true,
  },
  {
    date: "2025.09",
    title: "feat: UMC 9기 Web 챌린저 참여",
    description: "가천대학교 University Makeus Challenge 9기 (2025.09~)",
    branches: ["feature/club", "origin/feature/club"],
    color: "purple",
    position: 2,
    isBranch: true,
  },
  {
    date: "2024.12",
    title: "feat: 홈인스펙터 사전점검 업체 어플 유지보수",
    description: "Flutter(Web/App) + Node.js, 사전점검 어플 및 예약 웹페이지",
    branches: ["feature/homeinspector-maintenance"],
    color: "red",
    position: 3,
    isBranch: true,
  },
  {
    date: "2025.01",
    title: "feat: 홈인스펙터 업체 안전점검 어플리케이션 개발",
    description: "사전점검 업체 안전점검 어플 개발 (2025.01~2025.04)",
    branches: ["feature/homeinspector-dev", "origin/feature/homeinspector-dev"],
    color: "red",
    position: 3,
    isBranch: true,
  },
  {
    date: "2025.11.22",
    title: "🥇 Ne(o)rdinary Hackathon 우수상",
    description: "Node.js & Infra 프로젝트",
    branches: ["feature/price", "origin/feature/price"],
    color: "gold",
    position: 0,
  },
];
